# golangci-lint configuration for CI/CD
# This configuration is compatible with golangci-lint-action in GitHub Actions

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused

issues:
  exclude-use-default: false

run:
  timeout: 5m
